### ISSUE TITLE
Hardcode list of well know peers

### ISSUE THREAD

**Issue by altafan** [vulpemventures/neutrino-elements#5]
Do you think it would be valuable for the node to have a list of addresses of well-known peers to connect to?
Probably this is not necessary with a good peer discovery, but as long as it's not yet a feature, it would be nice for clients making use of this project to not be forced to provide peers' addresses when starting the node.

**Comment by tiero** [comment]
You need to know which node serves compact block filters, not sure this can be discovered?

I would prefer to not advertise public nodes (ours?) in a public repo TBH (blockstream.info may be well known). Maybe just a constant to be exported by this package
